In [6]:
import numpy as np

In [7]:
ax = np.array([1,2,3,4])

In [8]:
ax.shape

(4L,)

In [14]:
ax = np.array([1,2,3,4])
ax

array([1, 2, 3, 4])

In [15]:
def copy_not( array_input):
    array_input[0] = 110
    print 'hello'

In [16]:
copy_not(ax)

hello


In [17]:
ax

array([110,   2,   3,   4])

In [18]:
ay = [1,2,3,4]
ay

[1, 2, 3, 4]

In [19]:
copy_not(ay)

hello


In [20]:
ay

[110, 2, 3, 4]

In [5]:
ax[0]

1

In [6]:
ay = np.array([{'a':0}])

In [7]:
ay

array([{'a': 0}], dtype=object)

In [8]:
ay.shape

(1L,)

In [9]:
ay[0]

{'a': 0}

In [10]:
al = [{'a':0}]

In [11]:
al

[{'a': 0}]

In [12]:
al[0]

{'a': 0}

In [2]:
 x = np.matrix(np.arange(12)); x

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [4]:
x.A1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
 x.getA1()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [1]:
import graphlab as gl
import numpy as np
import matplotlib.pyplot as plt 

%matplotlib inline

'''Check GraphLab Create version'''
from distutils.version import StrictVersion
assert (StrictVersion(gl.version) >= StrictVersion('1.8.5')), 'GraphLab Create must be version 1.8.5 or later.'

In [2]:
# import wiki data
wiki = gl.SFrame('people_wiki.gl/')
wiki

[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\ONE\AppData\Local\Temp\graphlab_server_1508978361.log.0


This non-commercial license of GraphLab Create for academic use is assigned to wsdgh@qq.com and will expire on October 22, 2018.


Columns:
	URI	str
	name	str
	text	str

Rows: 59071

Data:
+-------------------------------+---------------------+
|              URI              |         name        |
+-------------------------------+---------------------+
| <http://dbpedia.org/resour... |    Digby Morrell    |
| <http://dbpedia.org/resour... |    Alfred J. Lewy   |
| <http://dbpedia.org/resour... |    Harpdog Brown    |
| <http://dbpedia.org/resour... | Franz Rottensteiner |
| <http://dbpedia.org/resour... |        G-Enka       |
| <http://dbpedia.org/resour... |    Sam Henderson    |
| <http://dbpedia.org/resour... |    Aaron LaCrate    |
| <http://dbpedia.org/resour... |   Trevor Ferguson   |
| <http://dbpedia.org/resour... |     Grant Nelson    |
| <http://dbpedia.org/resour... |     Cathy Caruth    |
+-------------------------------+---------------------+
+-------------------------------+
|              text             |
+-------------------------------+
| digby morrell born 10 octo... |
| alfred j lewy aka sandy le... |
| harpdog brown is a singer ... |
| franz rottensteiner born i... |
| henry krvits born 30 decem... |
| sam henderson born october... |
| aaron lacrate is an americ... |
| trevor ferguson aka john f... |
| grant nelson born 27 april... |
| cathy caruth born 1955 is ... |
+-------------------------------+
[59071 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [6]:
len(wiki['text'])

59071