In [6]:
import numpy as np

In [7]:
ax = np.array([1,2,3,4])

In [8]:
ax.shape

(4L,)

In [14]:
ax = np.array([1,2,3,4])
ax

array([1, 2, 3, 4])

In [15]:
def copy_not( array_input):
    array_input[0] = 110
    print 'hello'

In [16]:
copy_not(ax)

hello


In [17]:
ax

array([110,   2,   3,   4])

In [18]:
ay = [1,2,3,4]
ay

[1, 2, 3, 4]

In [19]:
copy_not(ay)

hello


In [20]:
ay

[110, 2, 3, 4]

In [5]:
ax[0]

1

In [6]:
ay = np.array([{'a':0}])

In [7]:
ay

array([{'a': 0}], dtype=object)

In [8]:
ay.shape

(1L,)

In [9]:
ay[0]

{'a': 0}

In [10]:
al = [{'a':0}]

In [11]:
al

[{'a': 0}]

In [12]:
al[0]

{'a': 0}

In [2]:
 x = np.matrix(np.arange(12)); x

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [4]:
x.A1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
 x.getA1()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])